global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "api-obervability-job"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["192.168.0.131:8080"]
        labels:
          application: "api-observability"
